### ISSUE TITLE
Deserialization of RecordTypeId fails in target org

### ISSUE THREAD

**Issue by up2go-rsoesemann** [afawcett/apex-sobjectdataloader#14]
I serialized data using Record Types. When I deserialize this data in another org it fails as the RecordTypeIds change from org to org, even when part of a managed package.

Is there anything I can do? String replacement?

**Comment by afawcett** [comment]
This should help... https://github.com/afawcett/apex-sobjectdataloader/blob/master/apex-sobjectdataloader/src/classes/SObjectDataLoaderTest.cls#L116

Its a callback to allow you to hook into the deserialize, this might allow you to switch in a proper Record Type ID from the target org.

**Comment by afawcett** [comment]
You may need to put a formula field on the object to serialie the RecordType name unless you can infer it during deserialize.

**Comment by up2go-rsoesemann** [comment]
Why is it not possible to serialize the RecordType? I then could infer the correct Ids from the Devleoper Name.

**Comment by afawcett** [comment]
RecordType is a system metadata object, not Apex DML access.

**Comment by afawcett** [comment]
If you create formula field that emits the record type name, you can then use this in the callback to associate by name with the correct id in the receiving org.

**Comment by up2go-rsoesemann** [comment]
Hy Andrew,

I thought of that as well, but the SObjectDataloader skips formula field during serialization. I even commented out that portion of the code. Then it fails on Deserialization as those fields can not be written. I could not think of a way to stop the code to not deserialize some fields.

Any idea how to do that? If there is any we would love to contribute that to the repo.

**Comment by afawcett** [comment]
Hmmmmmm that is a shame, i'm on holiday at present, will give it some thought. It may need a physical field with a Field Update workflow. But thats really going round the houses tbh...

**Comment by up2go-rsoesemann** [comment]
I just realized that the latest version of the dataloader has awesome recordtype support. I love this project. You saved our sprint ;-)!

**Comment by afawcett** [comment]
Oh man, so it does! That was contributed by @Sonal4J and i completely forgot! So thanks in the end to @Sonal4J :+1:

**Comment by Sonal4J** [comment]
Record Type support was added by @afaubel . Thanks for the contribution.

**Comment by afawcett** [comment]
Ah ok apologies @afaubel, indeed many thanks, great to see so many contributions to this!
