### ISSUE TITLE
Unpacked lookup fields pointing to unpackaged objects are not (de)serialized when from within a managed package

### ISSUE THREAD

**Issue by up2go-rsoesemann** [afawcett/apex-sobjectdataloader#16]
The title basically says it all. We have packaged this class to implement a (tree) clone functionality on a packaged custom object. 

In our configuration we define to serialize a parent and two child objects (all part of our package). A customer has addedThe problem is that custom fields (unpackaged ones) are not clones why serializing and deserializing.

Is there something we have to configure to make that work?

**Comment by up2go-rsoesemann** [comment]
Provided my local fix as Pull Request #17

**Comment by afawcett** [comment]
Thanks! :+1:
