### ISSUE TITLE
Method does not exist or incorrect signature: [SObjectDataLoader.SerializeConfig].addToUserFieldBlackList(Map>)

### ISSUE THREAD

**Issue by afawcett** [afawcett/apex-sobjectdataloader#19]
This compile issue was reported here https://github.com/afawcett/githubsfdeploy/issues/15

**Comment by afawcett** [comment]
@up2go-rsoesemann please can you take a look at this issue, it seems the code in the repo does not compile as it is currently? Looks like you may have deleted the addToUserFieldBlackList method in this last set of changes (though i cannot see that directly looking at the history).

**Comment by rsoesemann** [comment]
@afawcett This seems to be a method name change introduce in the @Sonal4J  merge before my PR. Methods switched their name from blacklist to whitelist (they do the same). I indeed had to rename them in my org to make the class run. But this should also be true for other users.

You decide how to call them. Eighter we rename the methods in the tests or the class itsself.

**Comment by afawcett** [comment]
@Sonal4J Can you please take a look, did you forget to update the test?

**Comment by Sonal4J** [comment]
I will fix the issue

**Comment by afawcett** [comment]
:+1:

**Comment by Sonal4J** [comment]
It seems that @rsoesemann has not developed on the latest code. I updated names from blacklist to whitelist as we are blacklisting the fields and childrelationships. Thus, the testmethods also have reference to the variable names as blacklist and not whitelist

**Comment by afawcett** [comment]
Ah i see, so how do we resolve this?

**Comment by up2go-rsoesemann** [comment]
Maybe I don't get it, but when I look at the state of the repo before my changes this error already exists. 

I again downloaded both classes from the last commit before my pull request https://github.com/afawcett/apex-sobjectdataloader/commit/46c031aebff09474b743edb6140fc21eddb05bf7 and the test won't even save.

@afawcett Feel free to reset your repo to a state before where everything worked fine and I will create a new pull request.

**Comment by PimdeVos** [comment]
I don't know if this helps but:

I managed to succesfully deploy master branch to salesforce after renaming "WhiteList" methods "BlackList". (the issue seems to be a simple naming discrepancy between the test class refering to the methods as BlackList and the normal class defining them under the name WhiteList.)

I think BlackList is more appropriate cause of the reasons named by @Sonal4J.

**Comment by afawcett** [comment]
Thanks @PimdeVos that certainly sounds cheaper all round way to resolve this, @Sonal4J do you agree?

**Comment by Sonal4J** [comment]
Yes I agree.

**Comment by RandyTrigg** [comment]
I just got the same compile error when deploying to my sandbox.  Is there a timeline for completing the fix, or a work-around in the meantime?

Thanks!

**Comment by RandyTrigg** [comment]
Okay, I followed @PimdeVos and renamed WhiteList methods to BlackList to get the test class to save. But now running the tests generates a bunch of errors.  At least some of the errors seem to be related to the changes that were made recently, for example, around currency and record types.  I'm trying to comment out those bits as we don't need them for our case, but perhaps I don't have the right test class?  Are others able to run the tests once the methods are renamed?

THanks!

**Comment by afawcett** [comment]
@RandyTrigg, @Sonal4J has kindly submitted a PR, which i've now merged that resolved this. Thanks all!
