### ISSUE TITLE
Error when deploying the package

### ISSUE THREAD

**Issue by RedaBenh** [afawcett/apex-sobjectdataloader#20]
Hi,
I try to install the package through the button "Deploy to Salesforce"
I get the error unit test error: 
```

Failures:
classes/SObjectDataLoaderTest.cls(521,87):Method does not exist or incorrect signature: [SObjectDataLoader.SerializeConfig].addToUserFieldBlackList(Map>)


```

![image](https://cloud.githubusercontent.com/assets/1609466/13900445/ae376ed4-ee06-11e5-8297-b2f286183884.png)

**Comment by afawcett** [comment]
This is a duplicate of this issue https://github.com/afawcett/apex-sobjectdataloader/issues/19
