### ISSUE TITLE
DUPLICATES_DETECTED Error in testOmitCompoundFieldsForAccount

### ISSUE THREAD

**Issue by up2go-sschwarz** [afawcett/apex-sobjectdataloader#23]
With [Spring 16](https://docs.releasenotes.salesforce.com/en-us/spring16/release-notes/rn_general_duplicate_management_on_for_new_orgs.htm) duplicate rules are automaticly activated for new orgs.
This includes a duplicate rule for Accounts, what makes this Test failing:
SObjectDataLoaderTest.testOmitCompoundFieldsForAccount: line 679

Workaround: deactive the rule (Setup quick search: "Duplicate Rules")
Fix would be nice though, so tests run intuitively :+1:

**Comment by afawcett** [comment]
Good spot, thanks! Logged as bug.
