### ISSUE TITLE
SObjectDataLoader class is not able to search relationship for more than 3 child depth

### ISSUE THREAD

**Issue by ParasKumar** [afawcett/apex-sobjectdataloader#32]
```
new SObjectDataLoader.SerializeConfig()
                               .followChild(B__c.A__c)
                               .followChild(C__c.B__c)
                               .followChild(D__c.C__c)
                               .followChild(E__c.D__c)
```
In above scenario, In A__c record, reocord for E__c object is not being queried. I open the debug log to see if the SOQL for E__c is being done whenever A__c record is open in vf page, but there is no any SOQL is being fired. I looked into searchRelationships() method of SObjectDataLoader class where there is limitation of only child depth upto 3 or lookupdepth upto 2. But in my case my child depth (or lookup depth) is more than 3. How to solve this kind of issue. Please help.

**Comment by afawcett** [comment]
Have you tried letting the library auto configure?

**Comment by ParasKumar** [comment]
Thanks for your reply. I just slightly modified the iteration condition in 
`private static void serialize()` method as   `if(lookupDepth > 3 || childDepth > 4)
            return;`
Now it is working fine. Thanks for your great support.

**Comment by afawcett** [comment]
No problem. 👍
