### ISSUE TITLE
Testmethod is not compatible with SFDC Platform Encryption

### ISSUE THREAD

**Issue by cropredyHelix** [afawcett/apex-sobjectdataloader#34]
If you have this class in your org and you choose to implement SFDC Platform Encryption (deterministic) on Account.Name, the testmethods will prevent you from doing so because you can't do `LIKE 'xxx'` on encrypted fields.

[Reference 1](https://help.salesforce.com/articleView?id=security_pe_deterministic_considerations.htm&type=5)

Example:

```
Apex Class: SObjectDataLoaderTest, line 430, column 47:
Select count() from Account where Name like 'TestAccount'
                                  ^
ERROR at Row:1:Column:35
The operator like is not supported on an encrypted field
```

**Comment by afawcett** [comment]
Merged, thanks @cropredyHelix 👍
