### ISSUE TITLE
No such column 'BillingAddress' on entity 'Account'.

### ISSUE THREAD

**Issue by rsoesemann** [afawcett/apex-sobjectdataloader#5]
The test class uses a field that is still in beta (2014). It fails in most orgs and should be replaced by something GA.

Stacktrace:

```
Class.UP2GO_2F.SObjectDataLoader.serialize: line 525, column 1
Class.UP2GO_2F.SObjectDataLoader.serialize: line 284, column 1
Class.UP2GO_2F.SObjectDataLoader.serialize: line 237, column 1
Class.UP2GO_2F.SObjectDataLoaderTest.serializeIdWithDifferentSObjectTypes: line 387, column 1
```

**Comment by miteshsura** [comment]
I saw same error message. For me the test class worked with I ran using UI and developer console (surprised??) but not when uploading new manged package. 

I changed the version from 28 to 31. It worked fine then.
