### ISSUE TITLE
Tests fail with System.QueryException: Implementation restriction

### ISSUE THREAD

**Issue by up2go-rsoesemann** [afawcett/apex-sobjectdataloader#8]
I have the latest version of both classes and when I run the test I get 6 fails with 

System.QueryException: Implementation restriction: CollaborationGroupRecord requires a filter by a single Id, CollaborationGroupId or RecordId using the equals operator

**Comment by afawcett** [comment]
This seems to be a Spring'15 change, looks like one thats leaked through despite the platform API not having been changed.... :-1: I think the fix will be to upgrade classes API version and add this object/relationship to the exclusion list.

**Comment by up2go-rsoesemann** [comment]
I added `CollaborationGroupRecord` and `CollaborationGroupId` to the according whitelist (shouldn't they be called blacklists?!) and set class and test to version 32, but nothing changed :-(

```javascript
// Standard fields that are not included when using the auto config
		private Set<String> relationshipWhitelist = 
			new Set<String>
				{ 'OwnerId',
				  'CreatedById',
				  'LastModifiedById',
				  'RecordTypeId',
				  'ProfileId',
				  'CollaborationGroupId'
				};
				
		// Standard child relationships that are not included when using the auto config
		private Set<String> childRelationshipWhitelist = 
			new Set<String> 
				{ 'Shares', 
				  'ProcessInstances', 
				  'ProcessSteps', 
				  'Tasks', 
				  'ActivityHistories', 
				  'Attachments', 
				  'FeedSubscriptionsForEntity', 
				  'Events', 
				  'Notes', 
				  'NotesAndAttachments', 
				  'OpenActivities', 
				  'Histories', 
				  'Feeds',
				  'CollaborationGroupRecord'};		
	
```

**Comment by afawcett** [comment]
Hmmmm yeah should be called blacklists actually good point! And yeah that should have worked....

**Comment by mginou** [comment]
I think the child Relationship name that needs to be white/black listed is RecordAssociatedGroups.

        // Standard child relationships that are not included when using the auto config
        private Set<String> childRelationshipWhitelist = 
            new Set<String> 
                { 'Shares', 
                  'ProcessInstances', 
                  'ProcessSteps', 
                  'Tasks', 
                  'ActivityHistories', 
                  'Attachments', 
                  'FeedSubscriptionsForEntity', 
                  'Events', 
                  'Notes', 
                  'NotesAndAttachments', 
                  'OpenActivities', 
                  'Histories', 
                  'Feeds',
                  'RecordAssociatedGroups'
                };

**Comment by up2go-rsoesemann** [comment]
mginou: That indeed helped! Thanks a lot.

**Comment by up2go-rsoesemann** [comment]
Maybe afawcett can merge this into the code or you can provide this a a pull request ;-)

**Comment by afawcett** [comment]
@mginou @up2go-rsoesemann nice work, yes, i'm a little busy at the mo, but not enough to click the merge button a PR for sure! Thanks again! :+1:
